apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonconnector
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: nonconnector
  template:
    metadata:
      labels:
        app: nonconnector
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: nonconnector-sa
      containers:
        - name: rubrion-nonconnector
          image: ghcr.io/rubrionmc/nonconnector:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.2"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nonconnector
spec:
  type: ClusterIP
  selector:
    app: nonconnector
  ports:
    - port: 25575
      targetPort: 25575