apiVersion: v1
kind: Namespace
metadata:
  name: {{PREFIX}}-proxy
  labels:
    environment: {{ENVIRONMENT}}
    identity: proxy

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{PREFIX}}-game
  labels:
    environment: {{ENVIRONMENT}}
    identity: game

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{PREFIX}}-infra
  labels:
    environment: {{ENVIRONMENT}}
    identity: infra

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{PREFIX}}-api
  labels:
    environment: {{ENVIRONMENT}}
    identity: api

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{PREFIX}}-web
  labels:
    environment: {{ENVIRONMENT}}
    identity: web