apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{PREFIX}}-quota
  namespace: {{NAMESPACE}}-proxy
spec:
  hard:
    limits.memory: {{MEMORY_USAGE_LIMIT}}
    limits.cpu: {{CPU_USAGE_LIMIT}}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{PREFIX}}-quota
  namespace: {{NAMESPACE}}-game
spec:
  hard:
    limits.memory: {{MEMORY_USAGE_LIMIT}}
    limits.cpu: {{CPU_USAGE_LIMIT}}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{PREFIX}}-quota
  namespace: {{NAMESPACE}}-proxy
spec:
  hard:
    limits.memory: {{MEMORY_USAGE_LIMIT}}
    limits.cpu: {{CPU_USAGE_LIMIT}}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{PREFIX}}-quota
  namespace: {{NAMESPACE}}-api
spec:
  hard:
    limits.memory: {{MEMORY_USAGE_LIMIT}}
    limits.cpu: {{CPU_USAGE_LIMIT}}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{PREFIX}}-quota
  namespace: {{NAMESPACE}}-web
spec:
  hard:
    limits.memory: {{MEMORY_USAGE_LIMIT}}
    limits.cpu: {{CPU_USAGE_LIMIT}}