# the secret for pulling images from GitHub Container Registry (GHCR)
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: {{PREFIX}}-{{NAMESPACE}}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: | 
    {
      "auths": {
        "ghcr.io": {
          "username": "{{GITHUB_USERNAME}}",
          "password": "{{GITHUB_TOKEN}}",
          "email":"{{GITHUB_EMAIL}}",
          "auth":"{{GITHUB_AUTH}}"
        }
      }
    }