apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-default
  namespace: {{PREFIX}}-{{NAMESPACE}}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---

# may don't put this in shared, but for now it is easier to manage
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-environment
  namespace: {{PREFIX}}-{{NAMESPACE}}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: {{ENVIRONMENT}}

  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              environment: {{ENVIRONMENT}}

---