apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pod-disruption-budget
  namespace: {{PREFIX}}-{{NAMESPACE}}
spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: {{NAMESPACE}}