apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: {{PREFIX}}-{{NAMESPACE}}
spec:
  type: LoadBalancer

  selector:
    app: {{NAMESPACE}}

  ports:
    - name: minecraft
      port: 25565
      targetPort: {{PORT:minecraft}}
      protocol: TCP

  externalTrafficPolicy: Local