# the domain name of the server, e.g. rubrion.net
exposed_domain: rubrion.lab

# schould claim domain localy only use for local development
claim_domain_localy: true

# the max Memory Usage (1Gi = 1 Gigabyte, 1Mi = 1 Mebibyte)
memory_usage_limit: 16Gi

# the max CPU Usage (100% = 1 CPU Core)
cpu_usage_limit: 600%

# the standart game server count, in pord 3/2
game_server_minimal: 1

dev_enviroment: true

# the images to be used in the project
images:
  # the link to the dockerhub / pull page, the image name and the version to be used
  postgresql:
    link: "https://hub.docker.com/_/postgresql"
    image: postgresql
    version: 18.3n
    intertnal: false

  nats:
    link: "https://hub.docker.com/_/nats"
    image: nats
    version: 2.9.17
    intertnal: false

  dragonfly:
    link: "https://hub.docker.com/r/dragonflydb/dragonfly"
    image: dragonflydb/dragonfly
    version: v1.27.1
    intertnal: false

  fallback:
    link: "https://hub.docker.com/r/itzg/minecraft-server"
    image: itzg/minecraft-server
    version: 1.20.4
    intertnal: true

# the ports for the exposing
ports:
  # the port to host minecraft on (25565 is the default minecraft port)
  minecraft: 25565

# the secrets to be used in the project
# values that ar _ get randomly generated on each run, but can be overridden by setting them here
secrets:
  # dragonfly / redis-compatible cache
  dragonfly-pass: "_"

  # nats message broker
  nats-user: "nats-svc"
  nats-pass: "_"

  # postgres superuser (used only by the statefulset init)
  sql-root-user: "postgres"
  sql-root-pass: "_"
  sql-db: "app"

  # postgres writer (backend services)
  sql-writer-user: "writer"
  sql-writer-pass: "_"

  # postgres reader (api, reporting – read-only)
  sql-reader-user: "reader"
  sql-reader-pass: "_"